# Generated by Django 4.2.2 on 2023-07-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ComplaintMS', '0002_alter_profile_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='collegename',
        ),
    ]
